### ISSUE TITLE
triples with aliased @id and @base are missing at root level

### ISSUE THREAD

**Issue by jmvanel** [filip26/titanium-json-ld#61]
**Describe the bug**
Two triples corresponding to @id `"id" : "54141546"` at root level in the JSON are lost.
Both @id 's are associated to a @base .
So there is just one triple left, corresponding to the inner JSON block :
```turtle
<https://www.inaturalist.org/users/3295956>
  <http://xmlns.com/foaf/0.1/img> 
    <https://static.inaturalist.org/attachments/users/icons/3295956/thumb.jpg?1594113662>
```
(works fine with Distiller & JS-LD Playground)

**To Reproduce**
Prepare files
```shell
echo '{
  "uri" : "54141546" ,
  "description" : "Aucune fleur ou fruit, glauque",
  "user" : {
    "id" : "3295956",
    "icon" : "https://static.inaturalist.org/attachments/users/icons/3295956/thumb.jpg?1594113662"
  } }' > test-bug-OK.json
echo '{ "@context": {
  "foaf": "http://xmlns.com/foaf/0.1/",
  "rdfs" : "http://www.w3.org/2000/01/rdf-schema#" ,
  "@base" : "https://api.inaturalist.org/v1/observations/" ,  
  "uri": "@id",
  "description" : "rdfs:comment" ,
  "user" : {
     "@id": "foaf:maker",
     "@context": {
      "icon" : { "@id": "foaf:img", "@type": "@id" } ,
      "@base" : "https://www.inaturalist.org/users/" ,
      "id" : "@id"
    }
  }
} }' > test-bug.context-OK.jsonld
```
Java code 
```java
String dir = "file:////home/jmv/test/"
String uri = dir + "test-bug-OK.json";
String context = dir + "test-bug.context-OK.jsonld";
JsonLdOptions options = new JsonLdOptions();
options.setExpandContext(context);
System.println(  JsonLd.toRdf( uri ) . options(options) . get() )
```
**Expected behavior**
Like with Distiller:
```turtle
<https://api.inaturalist.org/v1/observations/54141546> <http://xmlns.com/foaf/0.1/maker> <https://www.inaturalist.org/users/3295956> .
<https://api.inaturalist.org/v1/observations/54141546> <http://www.w3.org/2000/01/rdf-schema#comment> "Aucune fleur ou fruit, glauque" .
<https://www.inaturalist.org/users/3295956> <http://xmlns.com/foaf/0.1/img> <https://static.inaturalist.org/attachments/users/icons/3295956/thumb.jpg?1594113662> 
```
**Additional context**
NOTE : to be able to test I commented out the faulty Java code that prevents use of file: URL's , see preceding issue .

**Comment by filip26** [comment]
fixed by #68

**Comment by filip26** [comment]
@jmvanel please verify, the attached test passes. thank you.

**Comment by jmvanel** [comment]
> @jmvanel please verify, the attached test passes. thank you.

Alas, no, the original problem remains.
I saw you added the data of original issue as a test, but the test suite says:
```
Tests run: 1890, Failures: 0, Errors: 0, Skipped: 271
```

**Comment by filip26** [comment]
I'm sorry, but I cannot reconstruct the issue. I run the test manually as well. Please feel free to update [test 61](https://github.com/filip26/titanium-json-ld/blob/master/src/test/java/com/apicatalog/jsonld/issue/ToRdfIssue61Test.java)

(the test suite includes 1.0 tests and non-nomrative tests (the skipped ones).

**Comment by filip26** [comment]
thank you, There is something wrong when a context is referenced by URI.

btw. you can use this to print `RdfDataset` to `System.out`

```javascript
(new NQuadsWriter(new PrintWriter(System.out))).write(result);
```

**Comment by filip26** [comment]
The issue is that @base is not processed if a context is remote, it's related to issue #63

A workaround is to set the base manually. e.g.

```javascript
JsonLd.toRdf("file:/...").context("file:/...").base("https://api.inaturalist.org/v1/observations/").get()
```

**Comment by filip26** [comment]
The specification states:
```
If the expandContext option in options is set, update the active context using 
the Context Processing algorithm, passing the expandContext as local context
```
In your case an array containing one URL (the file:/... represented as a string) is passed to [Context Processing algorithm](https://www.w3.org/TR/json-ld11-api/#algorithm) as a local context and is processed by a step 5.2. 

This comment  [Question about base and remote contexts](https://github.com/w3c/json-ld-api/issues/505) suggests to remove @base after step 5.2.5.2 which is a step right after the given URL has been deferrenced.

I tend to close this issue and recommend to set a base explicitly as suggested above, please feel to re-open, to put more light on this.
